### ISSUE TITLE
Snort download and install operating system requirement 

### ISSUE THREAD

**Issue by sabarish-2020** [snort3/snort3#140] opened 2020-10-13 06:01 UTC
Hi All, 

I trying to use Snort for the first time so I would like to know if there is any specific operating system that would help smooth download and install the tool?

I currently use windows 10 and ubuntu 16.04 in the virtual box.

**Comment by Xiche** [comment] 2020-10-13 15:07
Duplicate of #141

**Closed by Xiche** 2020-10-13 15:07 UTC
