### ISSUE TITLE
ERROR: can't compile content '<SCRIPT'

### ISSUE THREAD

**Issue by bluesku** [snort3/snort3#160] opened 2021-02-24 15:02 UTC
Hey there, im experiencing this issue while running under ubuntu 18.04 

```
root@mypc:~/snort3-Plus# snort -c /usr/local/etc/snort/snort.lua
--------------------------------------------------
o")~   Snort++ 3.1.1.0
--------------------------------------------------
ERROR: can't compile content '<SCRIPT'
ERROR: can't compile content '</SCRIPT>'
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:

```
 also after run: `snort -c /usr/local/etc/snort/snort.lua`

```
--------------------------------------------------
o")~   Snort++ 3.1.1.0
--------------------------------------------------
ERROR: can't compile content '<SCRIPT'
ERROR: can't compile content '</SCRIPT>'
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
	ssh
	hosts
	host_cache
	pop
	so_proxy
	stream_tcp
	smtp
	gtp_inspect
	packets
	dce_http_proxy
	stream_icmp
	normalizer
	alerts
	rewrite
	ips
	stream_udp
	binder
	wizard
	appid
	search_engine
	file_id
	ftp_data
	ftp_server
	port_scan
	dce_http_server
	dce_smb
	dce_tcp
	telnet
	ssl
	sip
	rpc_decode
	netflow
	http_inspect
	network
	http2_inspect
	modbus
	host_tracker
	stream_user
	stream_ip
	trace
	back_orifice
	classifications
	dnp3
	active
	ftp_client
	decode
	daq
	stream
	references
	arp_spoof
	output
	process
	dns
	dce_udp
	imap
	stream_file
Finished /usr/local/etc/snort/snort.lua:
Loading /usr/local/etc/rules/snort3-community.rules:
Finished /usr/local/etc/rules/snort3-community.rules:
--------------------------------------------------
rule counts
       total rules loaded: 3488
               text rules: 3488
            option chains: 3488
            chain headers: 295
--------------------------------------------------
port rule counts
             tcp     udp    icmp      ip
     any     463      63     147      22
     src     305      16       0       0
     dst    2293     245       0       0
    both       6       9       0       0
   total    3067     333     147      22
--------------------------------------------------
ips policies rule stats
              id  loaded  shared enabled    file
               0    3488       0    3488    /usr/local/etc/snort/snort.lua
--------------------------------------------------
flowbits
                  defined: 32
              not checked: 7
                  not set: 10
--------------------------------------------------
service rule counts          to-srv  to-cli
                   dcerpc:        4       3
                      dns:      123       7
                     file:        2       0
                      ftp:       87       4
                 ftp-data:        3      53
                     http:     1700     195
                    http2:     1700     195
                     imap:       37      53
                      irc:        4       1
                 kerberos:        2       0
                    mysql:        3       0
              netbios-dgm:        1       1
               netbios-ns:        4       3
              netbios-ssn:       60      14
                     nntp:        2       0
                     pop3:       25      53
                      rdp:        1       0
                      sip:        5       5
                     smtp:       71       2
                     snmp:       18       7
                      ssl:       18      36
                   sunrpc:       68       4
                   telnet:       12       6
                     tftp:        1       0
                     wins:        1       0
                    total:     3952     642
--------------------------------------------------
fast pattern port groups        src     dst     any
                   packet:       58     153       4
--------------------------------------------------
fast pattern service groups  to-srv  to-cli
                   packet:       22      18
                      key:        5       0
                   header:        3       6
                     body:        2       0
                     file:        9       5
                   method:        2       0
                stat_code:        0       2
                   cookie:        2       0
--------------------------------------------------
search engine
                instances: 278
                 patterns: 6578
            pattern chars: 110771
               num states: 76229
         num match states: 6343
             memory scale: MB
             total memory: 1.83196
           pattern memory: 0.255933
        match list memory: 0.412251
        transition memory: 1.13726
ERROR: appid: could not open /usr/local/etc/rules/lightspd/odp/appMapping.data
--------------------------------------------------
pcap DAQ configured to passive.
FATAL: see prior 3 errors (0 warnings)
Fatal Error, Quitting..

```

**Comment by Xiche** [comment] 2021-02-24 15:16
Dupe of #158 and #160.

**Closed** 2021-02-24 15:15 UTC
