### ISSUE TITLE
Snort 3 Ignores Configured Syslog Facility and Level

### ISSUE THREAD

**Issue by foxfire-auspex** [snort3/snort3#268] opened 2022-09-12 13:40 UTC
Hello,

Currently it seems Snort does not correctly apply configuration pertaining to syslog facility and level.

I am running Snort 3 (version 3.1.40.0, installed from CERT Linux Forensics Tools Repository) via systemd under Rocky Linux 9.

Here is the ExecStart parameter of my unit file - please note the presence of the `-A` flag.:
`/usr/bin/snort -v -D -c /etc/snort3/snort.lua --plugin-path /etc/snort3/so_rules/ -u snort -g snort -k none -i enp1s0 -A alert_syslog`

Additionally, here's the relevant part of my snort.lua config file:

`alert_syslog =
{
    facility = local6,
    level = warning
}`

All other possible logging options are commented out.

Configuration and rules load without issue. Here's a snippet of `journalctl -u snortd@enp1s0` after a `systemctl restart snortd@enp1s0`:

> Sep 12 13:16:45 rocky9vm snort[973]: --------------------------------------------------
Sep 12 13:16:45 rocky9vm snort[973]: o")~   Snort++ 3.1.40.0
Sep 12 13:16:45 rocky9vm snort[973]: --------------------------------------------------
Sep 12 13:16:45 rocky9vm snort[973]: Loading /etc/snort3/snort.lua:
Sep 12 13:16:45 rocky9vm snort[973]: Loading snort_defaults.lua:
Sep 12 13:16:45 rocky9vm snort[973]: Finished snort_defaults.lua:
Sep 12 13:16:45 rocky9vm snort[973]:         Lua Allowlist Keywords for /etc/snort3/snort.lua:
Sep 12 13:16:45 rocky9vm snort[973]:                 default_classifications, default_ftp_server, default_gtp,
Sep 12 13:16:45 rocky9vm snort[973]:                 default_hi_port_scan, default_http_inspect, default_js_norm_ident_ignore,
Sep 12 13:16:45 rocky9vm snort[973]:                 default_js_norm_prop_ignore, default_low_port_scan, default_med_port_scan,
Sep 12 13:16:45 rocky9vm snort[973]:                 default_references, default_smtp, default_variables, default_wizard,
Sep 12 13:16:45 rocky9vm snort[973]:                 ftp_command_specs, gtp_v0_info, gtp_v0_msg, gtp_v1_info, gtp_v1_msg,
Sep 12 13:16:45 rocky9vm snort[973]:                 gtp_v2_info, gtp_v2_msg, http_methods, icmp_hi_sweep, icmp_low_sweep,
Sep 12 13:16:45 rocky9vm snort[973]:                 icmp_med_sweep, ip_hi_decoy, ip_hi_dist, ip_hi_proto, ip_hi_sweep,
Sep 12 13:16:45 rocky9vm snort[973]:                 ip_low_decoy, ip_low_dist, ip_low_proto, ip_low_sweep, ip_med_decoy,
Sep 12 13:16:45 rocky9vm snort[973]:                 ip_med_dist, ip_med_proto, ip_med_sweep, netflow_versions, sip_requests,
Sep 12 13:16:45 rocky9vm snort[973]:                 smtp_default_alt_max_command_lines, tcp_hi_decoy, tcp_hi_dist, tcp_hi_ports,
Sep 12 13:16:45 rocky9vm snort[973]:                 tcp_hi_sweep, tcp_low_decoy, tcp_low_dist, tcp_low_ports, tcp_low_sweep,
Sep 12 13:16:45 rocky9vm snort[973]:                 tcp_med_decoy, tcp_med_dist, tcp_med_ports, tcp_med_sweep, telnet_commands,
Sep 12 13:16:45 rocky9vm snort[973]:                 udp_hi_decoy, udp_hi_dist, udp_hi_ports, udp_hi_sweep, udp_low_decoy,
Sep 12 13:16:45 rocky9vm snort[973]:                 udp_low_dist, udp_low_ports, udp_low_sweep, udp_med_decoy, udp_med_dist,
Sep 12 13:16:45 rocky9vm snort[973]:                 udp_med_ports, udp_med_sweep
Sep 12 13:16:45 rocky9vm snort[973]:         alerts
Sep 12 13:16:45 rocky9vm snort[973]:         daq
Sep 12 13:16:45 rocky9vm snort[973]:         decode
[...]
Sep 12 13:16:45 rocky9vm snort[973]:         output
Sep 12 13:16:45 rocky9vm snort[973]:         active
Sep 12 13:16:45 rocky9vm snort[973]:         so_proxy
Sep 12 13:16:45 rocky9vm snort[973]:         trace
Sep 12 13:16:45 rocky9vm snort[973]: Finished /etc/snort3/snort.lua:
Sep 12 13:16:45 rocky9vm snort[973]: Loading file_id.rules_file:
Sep 12 13:16:45 rocky9vm snort[973]: Loading /usr/etc/snort/file_magic.rules:
Sep 12 13:16:45 rocky9vm snort[973]: Finished /usr/etc/snort/file_magic.rules:
Sep 12 13:16:45 rocky9vm snort[973]: Finished file_id.rules_file:
Sep 12 13:16:45 rocky9vm snort[973]: Loading ips.rules:
Sep 12 13:16:45 rocky9vm snort[973]: Loading /etc/snort3/rules/pulledpork3.rules:
Sep 12 13:16:45 rocky9vm snort[973]: Finished /etc/snort3/rules/pulledpork3.rules:
Sep 12 13:16:45 rocky9vm snort[973]: Finished ips.rules:
Sep 12 13:16:45 rocky9vm snort[973]: --------------------------------------------------
Sep 12 13:16:45 rocky9vm snort[973]: ips policies rule stats
Sep 12 13:16:45 rocky9vm snort[973]:               id  loaded  shared enabled    file
Sep 12 13:16:45 rocky9vm snort[973]:                0    9355       0    9355    /etc/snort3/snort.lua
Sep 12 13:16:45 rocky9vm snort[973]: --------------------------------------------------

Still, Snort does not log using the configured facility (local6) and level (warning). Here's a sample log message I got via `journalctl -o json-pretty -u snortd@enp1s0`:

> {
        "_SOURCE_REALTIME_TIMESTAMP" : "1662989840951090",
        "_SYSTEMD_SLICE" : "system-snortd.slice",
        "_UID" : "1000",
        "SYSLOG_FACILITY" : "4",
        "SYSLOG_PID" : "2501",
        "PRIORITY" : "6",
        "_EXE" : "/usr/bin/snort",
        "_SYSTEMD_INVOCATION_ID" : "e16900b469034a438c52b549fca5e106",
        "__REALTIME_TIMESTAMP" : "1662989840951746",
        "_GID" : "1000",
        "SYSLOG_TIMESTAMP" : "Sep 12 13:37:20 ",
        "_HOSTNAME" : "rocky9vm",
        "_CAP_EFFECTIVE" : "0",
        "SYSLOG_IDENTIFIER" : "snort",
        "_SELINUX_CONTEXT" : "system_u:system_r:snort_t:s0",
        "_COMM" : "snort",
        "__MONOTONIC_TIMESTAMP" : "1239829388",
        "__CURSOR" : "s=72c0f89640ed41c1b3028972115743ba;i=134f;b=3ee3d65febc24981bf66239fc5def5de;m=49e64b8c;t=5e87afebc29c2;x=2ba6f19b0252ded7",
        "_CMDLINE" : "/usr/bin/snort -v -D -c /etc/snort3/snort.lua --plugin-path /etc/snort3/so_rules/ -u snort -g snort -k none -i enp1s0 -A alert_syslog",
        "_SYSTEMD_UNIT" : "snortd@enp1s0.service",
        "_TRANSPORT" : "syslog",
        "_SYSTEMD_CGROUP" : "/system.slice/system-snortd.slice/snortd@enp1s0.service",
        "_PID" : "2501",
        "_MACHINE_ID" : "372d3f9cae6543798d63156a54051346",
        "MESSAGE" : "[1:1000000003:0] \"Snort Test TCP - OINK, OINK!\" {TCP} 192.168.REDACTED -> 192.168.REDACTED",
        "_BOOT_ID" : "3ee3d65febc24981bf66239fc5def5de"
}

I did my best trying to solve this myself by reading the Snort 3 Reference Manual, Snort 3 on CentOS 8 Stream (both from snort.org) and available commandline --help, but to no avail.

Thus, at this point I believe this to be a bug in Snort.

**Comment by dkyrylov** [comment] 2022-09-22 13:04
Thank you for reporting the issue. We are currently looking into potential causes, and will keep you updated about potential solutions.

**Comment by RaveNN-0** [comment] 2023-12-09 13:06
Any update on this ?

**Comment by snortadmin** [comment] 2023-12-11 19:40
If this is literally your config, as pasted above ...
```
alert_syslog = { facility = local6, level = warning }
```
... the problem is that facility and level take string values so you need 'local6' and 'warning'.

**Comment by RaveNN-0** [comment] 2023-12-12 00:00
> If this is literally your config, as pasted above ...
> 
> ```
> alert_syslog = { facility = local6, level = warning }
> ```
> 
> ... the problem is that facility and level take string values so you need 'local6' and 'warning'.
> 
> The help shows the correct usage for facility and warning:
> 
> ```
> $ src/snort --help-config alert_syslog
> enum alert_syslog.facility = 'auth': part of priority applied to each message { 'auth' | 'authpriv' | 'daemon' | 'user' | 'local0' | 'local1' | 'local2' | 'local3' | 'local4' | 'local5' | 'local6' | 'local7' }
> enum alert_syslog.level = 'info': part of priority applied to each message { 'emerg' | 'alert' | 'crit' | 'err' | 'warning' | 'notice' | 'info' | 'debug' }
> ```

That was the solution, you can close the issue I guess even though im not the original poster. Thanks !

**Closed** 2024-05-28 10:25 UTC
