### ISSUE TITLE
snort3 build error

### ISSUE THREAD

**Issue by hebtuerror404** [snort3/snort3#191] opened 2021-06-17 08:20 UTC
/home/xxxx/Desktop/snort3-master/src/codecs/ip/cd_ipv4.cc: In member function ‘virtual bool {anonymous}::Ipv4Codec::decode(const snort::RawData&, snort::CodecData&, DecodeData&)’:
/home/xxxx/Desktop/snort3-master/src/codecs/ip/cd_ipv4.cc:246:47: error: ‘const DAQ_NAPTInfo_t {aka const struct _daq_napt_info}’ has no member named ‘ip_layer’
     if (napti && codec.ip_layer_cnt == napti->ip_layer)
                                               ^~~~~~~~
src/codecs/ip/CMakeFiles/ip_codecs.dir/build.make:62: recipe for target 'src/codecs/ip/CMakeFiles/ip_codecs.dir/cd_ipv4.cc.o' failed
make[2]: *** [src/codecs/ip/CMakeFiles/ip_codecs.dir/cd_ipv4.cc.o] Error 1
CMakeFiles/Makefile2:614: recipe for target 'src/codecs/ip/CMakeFiles/ip_codecs.dir/all' failed
make[1]: *** [src/codecs/ip/CMakeFiles/ip_codecs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by mjs717** [comment] 2021-06-17 10:41
Yep, that's known, sorry about that. We're working on resolving that as soon as we can. The issue is that the latest DAQ release is behind by 1 commit. We had some technical difficulties yesterday in getting a new release pushed for it. In the meantime, you should be able to back off by 1 release for snort3 (i.e., pull tag 3.1.5.0 instead).

**Comment by mjs717** [comment] 2021-06-19 18:51
This should be resolved now. A new DAQ3 release has been pushed. Please pull the latest from libdaq (v3.0.4) along with the latest from snort3 (3.1.6.0). Let us know if you have any issues. Thanks!

**Closed** 2021-06-21 02:14 UTC
